package com.example.library2.utilities;

public enum MessageType {
    ERROR_PASSWORD,
    ERROR_NAME,
    SUCCESS,
    SEVER_RUN_OUT,
    ACCOUNT_EXIST,
    PHONE_EXIST,
    EMAIL_EXIST,
    UNEXPECTED_ERROR,
    FAIL_PASS,
    ACCOUNT_NOT_EXIST,
    HAD_LIKE,
    HAD_ORDERED,
    ORDERED_BY_ANOTHER,
    HAD_BORROWED,
    BORROWED_BY_OTHER,
    NOT_ORDER_YET,
    NOT_BORROW_YET,
    NOT_ENOUGH_POS,
    EMPLOYEE,
    MANAGEMENT,
    NO_POS
}
